# Generated by Django 4.0.2 on 2022-03-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('ActualQty', models.IntegerField()),
                ('limitQty', models.IntegerField()),
            ],
        ),
    ]
