# Generated by Django 4.0.2 on 2022-03-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockCompta', '0002_remove_article_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Takedate', models.DateField()),
                ('beneficiary', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('qte', models.IntegerField()),
                ('service', models.CharField(max_length=50)),
            ],
        ),
    ]
