# Generated by Django 4.0.2 on 2022-03-04 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StockCompta', '0003_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='Takedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
