# Generated by Django 4.0.2 on 2022-03-06 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockCompta', '0004_alter_sortie_takedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='Takedate',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
