# Generated by Django 4.0.2 on 2022-03-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockCompta', '0005_alter_sortie_takedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortie',
            name='Takedate',
        ),
        migrations.AddField(
            model_name='sortie',
            name='an',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='jour',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='mois',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='beneficiary',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='service',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
