# Generated by Django 4.0.2 on 2022-03-25 14:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StockCompta', '0007_alter_sortie_an_alter_sortie_jour_alter_sortie_mois'),
    ]

    operations = [
        migrations.CreateModel(
            name='personnel',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('numero', models.IntegerField()),
                ('service', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='priceClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime(2022, 3, 25, 15, 54, 18, 344975))),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='an',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='jour',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='label',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='mois',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='service',
        ),
        migrations.AddField(
            model_name='article',
            name='AddedDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 15, 54, 18, 346970)),
        ),
        migrations.AddField(
            model_name='sortie',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 15, 54, 18, 346970)),
        ),
        migrations.AddField(
            model_name='sortie',
            name='idArticle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StockCompta.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime(2022, 3, 25, 15, 54, 18, 345986))),
                ('idFournisseur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StockCompta.provider')),
                ('idUsername', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='idPrix',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StockCompta.priceclass'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='idPersonnel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StockCompta.personnel'),
        ),
    ]
