# Generated by Django 4.0.2 on 2022-03-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockCompta', '0008_personnel_priceclass_provider_remove_sortie_an_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='AddedDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='service',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='priceclass',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='Date',
            field=models.DateField(),
        ),
    ]
