# Generated by Django 4.0.2 on 2022-03-25 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockCompta', '0010_rename_priceclass_price_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='price',
        ),
    ]
