# Generated by Django 4.0.2 on 2022-03-26 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StockCompta', '0011_remove_article_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='idPrix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StockCompta.price_class'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='idFournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StockCompta.provider'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='idUsername',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='idArticle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StockCompta.article'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='idPersonnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StockCompta.personnel'),
        ),
    ]
