# Generated by Django 4.0.2 on 2022-03-26 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockCompta', '0013_rename_idprix_article_paramprix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ActualQty',
        ),
        migrations.CreateModel(
            name='Ligne_de_facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActualQty', models.IntegerField()),
                ('paramArticle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StockCompta.article')),
                ('paramBill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StockCompta.bill')),
            ],
        ),
    ]
