# Generated by Django 4.0.2 on 2022-04-04 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockCompta', '0014_remove_article_actualqty_ligne_de_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeDate', models.DateField()),
                ('idArticle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StockCompta.article')),
                ('idPrix', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StockCompta.price_class')),
            ],
        ),
    ]
